### ISSUE TITLE
Objekt kann nicht geladen werden

### ISSUE THREAD

**Issue by sgeier96** [sgeier96/CGA-RenderingCompetition-WS16-17#1]
Ich habe ein Objekt bereits in den jeweiligen Ordner gepackt. Ist ein Raumschiff. 
Allerdings ist der ObjectLoader nicht in der Lage den korrekt zu laden. 
-> Error beim compilieren

**Comment by sgeier96** [comment]
Unstimmigkeit gefunden:
In der Starcruiser.obj-Datei werden Texturen(?) mit mehr als 3 Dimensionen genutzt. 
Wenn man die in Eclipse öffnet, kann man die ganzen Koordinaten einsehen. Ganz unten, wo die 
Koordinaten mit "f" bezeichnet sind, sind die "übeltäter". 
Hier liegt also die mögliche Verbesserung des OBJLoaders.

**Comment by vdemizki** [comment]
Ich versuche mal dieses Problem zu lösen. Notfalls müssen wir mit Blender ein eigenes Objekt entwerfen.
