### ISSUE TITLE
Weltall als Hintergrund einbauen

### ISSUE THREAD

**Issue by sgeier96** [sgeier96/CGA-RenderingCompetition-WS16-17#14]
Schwarzer Hintergrund mit weißen Punkten (Sterne).
Diese weißen Punkte sollen sich allerdings, ähnlich wie die Kometen, am Raumschiff vorbei bewegen. 
Dabei ziehen sie Schweife hinter sich her, was den Eindruck erweckt, dass man sich in einer 
so hohen Geschwindigkeit fortbewegt.
Sehr ähnlich wie hier: https://www.youtube.com/watch?v=17WoOqgXsRM 
(Achtung, ANDERE Programmiersprache)

**Comment by vdemizki** [comment]
Sterne brauchen ein anderes Objekt.

**Comment by vdemizki** [comment]
Das mit dem Schweif ist etwas kompliziert. Ich würde es aufschieben, falls wir später noch Zeit haben.
