### ISSUE TITLE
Lichtquelle in der linken oberen Ecke einbauen (Sonne)

### ISSUE THREAD

**Issue by sgeier96** [sgeier96/CGA-RenderingCompetition-WS16-17#16]
Um auch den Punkt der Schatten simulieren zu können, müssen wir noch 
eine Lichtquelle einbauen. Dazu könnte sich einfach ein sehr heller Stern eignen (Sonne).
Falls man dann noch Zeit hat, auch evtl das aus dem Raumschiff kommende Licht einbauen.

**Comment by sgeier96** [comment]
Der Shadermode[1] nachdem man die Leertaste betätigt kann dafür verwendet & modifiziert werden.

**Comment by vdemizki** [comment]
Das Licht ist momentan vor der Sonne. Man müsste die Sonne wahrscheinlich transparent machen damit das Licht von innen leichten kann.
